spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:tes
    username: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true